# Generated by Django 5.0.1 on 2024-01-11 12:18

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('phone_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('opt', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'otps',
            },
            managers=[
                ('otps', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('firebase_token', models.CharField(blank=True, default='', max_length=200, null=True, unique=True)),
                ('dob', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('relation_goals', models.CharField(blank=True, max_length=100, null=True)),
                ('interest', models.CharField(blank=True, max_length=10, null=True)),
                ('activity', models.CharField(blank=True, max_length=30, null=True)),
                ('registered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('users', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('like_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_likes', to='users.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_likes', to='users.user')),
            ],
            options={
                'db_table': 'likes',
            },
            managers=[
                ('likes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserHobbies',
            fields=[
                ('hobbies_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hobbie', models.CharField(max_length=200)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'hobbies',
            },
            managers=[
                ('hobbies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('image_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=200, unique=True)),
                ('image_encode', models.CharField(max_length=200, unique=True)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'images',
            },
            managers=[
                ('images', django.db.models.manager.Manager()),
            ],
        ),
    ]
