# Generated by Django 5.0.1 on 2024-01-19 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_location_alter_userimage_image_encode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='users.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='firebase_token',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userhobbies',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='users.user'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.user'),
        ),
    ]
