# Generated by Django 5.0.1 on 2024-01-30 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_likes_sender_alter_user_firebase_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='users.user'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_likes', to='users.user'),
        ),
    ]
