# Generated by Django 5.0.1 on 2024-02-07 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_likes_receiver_alter_likes_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='image_encode',
        ),
    ]
