# Generated by Django 5.0.1 on 2024-02-07 23:30

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userimage_image_encode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('location_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('altitude', models.FloatField()),
                ('speed', models.FloatField()),
                ('speedAccuracy', models.FloatField()),
                ('heading', models.FloatField()),
                ('time', models.FloatField()),
                ('isMock', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='users.user')),
            ],
            options={
                'db_table': 'locations',
            },
            managers=[
                ('locations', django.db.models.manager.Manager()),
            ],
        ),
    ]
