# Generated by Django 5.0.1 on 2024-02-07 23:44

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userlocation'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userlocation',
            managers=[
                ('location', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterModelTable(
            name='userlocation',
            table='location',
        ),
    ]
