# Generated by Django 5.0.1 on 2024-02-15 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userlocation_managers_remove_user_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='image_encode',
            field=models.CharField(default='L371cr_3RKKFsqICIVNG00eR?d-r', max_length=200),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='users.user'),
        ),
    ]
