# Generated by Django 5.0.1 on 2024-03-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userimage_image_encode_alter_userlocation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='android_version',
            field=models.CharField(default='1.0.1', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='ios_version',
            field=models.CharField(default='1.0.1', max_length=50),
        ),
    ]
