# Generated by Django 5.0.4 on 2025-06-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessuser',
            name='business_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hardwareotp',
            name='otp',
            field=models.CharField(max_length=4),
        ),
    ]
