# Generated by Django 5.0.4 on 2025-06-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_backend', '0002_alter_businessuser_business_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
