# Generated by Django 5.2.4 on 2025-09-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_backend', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile_money_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='partial_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_timing',
            field=models.CharField(choices=[('pay_now', 'Pay Now'), ('pay_on_delivery', 'Pay on Delivery')], default='pay_on_delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pack_type',
            field=models.CharField(choices=[('Piece', 'Piece'), ('Dozen', 'Dozen')], default='Piece', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer')], default='cash_on_delivery', max_length=50),
        ),
    ]
