# Generated by Django 5.2.4 on 2025-11-19 21:11

import django.db.models.deletion
import hardware_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_backend', '0009_productbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.CharField(default=hardware_backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('Office', 'Office Supplies'), ('Maintenance', 'Maintenance'), ('Marketing', 'Marketing'), ('Utilities', 'Utilities'), ('Travel', 'Travel'), ('Other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('expense_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to='hardware_backend.businessuser')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to='hardware_backend.businessuser')),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-created_at'],
            },
        ),
    ]
