# Generated by Django 5.0.1 on 2024-01-11 12:18

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('feature_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('registered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'packages',
            },
            managers=[
                ('packages', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('feature_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('free', models.CharField(max_length=80)),
                ('paid', models.CharField(max_length=80)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.package')),
            ],
            options={
                'db_table': 'features',
            },
            managers=[
                ('features', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.user')),
            ],
            options={
                'db_table': 'subscriptions',
            },
            managers=[
                ('subscriptions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('transaction_number', models.CharField(max_length=100, unique=True)),
                ('reference_id', models.CharField(max_length=50, unique=True)),
                ('reference_type', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_channel', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.subscription')),
            ],
            options={
                'db_table': 'transactions',
            },
            managers=[
                ('transactions', django.db.models.manager.Manager()),
            ],
        ),
    ]
