# Generated by Django 5.0.1 on 2024-01-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='feature_id',
            new_name='package_id',
        ),
    ]
