# Generated by Django 5.0.1 on 2024-02-01 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_rename_feature_id_package_package_id'),
        ('users', '0004_alter_likes_receiver_alter_likes_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='subscription',
        ),
        migrations.AddField(
            model_name='package',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.package'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user'),
        ),
        migrations.AlterField(
            model_name='packagefeature',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='subscription.package'),
        ),
    ]
