# Generated by Django 5.0.1 on 2024-02-03 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_remove_transaction_subscription_package_days_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackageFeature',
        ),
    ]
